name: logs-push-to-main
on:
  push:
    branches: [ "main" ]

jobs:
  trabajo-de-mensajes:
    runs-on: ubuntu-latest 

    steps:
      - name: Get Repository
        uses: actions/checkout@v4

      - name: Log 1
        run: echo "¡Nuevo commit detectado en la rama principal (main)!"

      - name: Log 2
        run: echo "Iniciando el flujo de trabajo..."

      - name: Log 3
        run: echo "Realizando algunas verificaciones..."

      - name: Log 4
        run: echo "✅¡Flujo de trabajo completado exitosamente!"